services:
  fluxocaixaapi:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FluxoCaixaDB;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;Encrypt=False
      - Redis__Configuration=redis:6379
      - RabbitMq__HostName=rabbitmq
      - Elasticsearch__Uri=http://elasticsearch:9200
    depends_on:
      - sqlserver
      - redis
      - rabbitmq
      - elasticsearch
    command: ["./wait-for-it.sh", "sqlserver:1433", "--", "./wait-for-it.sh", "rabbitmq:5672", "--", "./wait-for-it.sh", "redis:6379", "--", "./wait-for-it.sh", "elasticsearch:9200", "--", "dotnet", "FluxoCaixaApi.dll"]  
    networks:
      - fluxo-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fluxocaixaapi
    networks:
      - fluxo-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: SenhaForte123!
      ACCEPT_EULA: "Y"      
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql  # Volume persistente para dados do SQL Server
    networks:
      - fluxo-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - fluxo-net

  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fluxo-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - fluxo-net

volumes:
  sql_data:
    driver: local

networks:
  fluxo-net:
    driver: bridge
